#!/bin/bash
# ============================================================
# Lab Data Stack — install.sh
# Guided first-time setup: checks dependencies, collects all
# credentials interactively, writes .env, and starts the stack.
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

# ─── Collect all values ──────────────────────────────────────

collect_values() {
  # ── Project name ─────────────────────────────────────────
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " Project"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  The project name is used for Docker container and"
  echo "  volume names. Use a short, lowercase identifier"
  echo "  (e.g. 'calibration', 'robolab-2026')."
  prompt_value "Project name" "" "true"
  PROJECT_NAME="$_REPLY"

  # ── PostgreSQL ───────────────────────────────────────────
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " PostgreSQL"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  prompt_value "Database username" "labuser"
  POSTGRES_USER="$_REPLY"

  prompt_value "Database password" "$(gen_secret)"
  POSTGRES_PASSWORD="$_REPLY"

  # ── NocoDB ───────────────────────────────────────────────
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " NocoDB"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  prompt_value "Admin email" "admin@lab.local"
  NOCODB_ADMIN_EMAIL="$_REPLY"

  prompt_value "Admin password" "$(gen_secret)"
  NOCODB_ADMIN_PASSWORD="$_REPLY"

  prompt_value "JWT secret (signs login sessions)" "$(gen_secret)"
  NOCODB_JWT_SECRET="$_REPLY"

  # ── Superset ─────────────────────────────────────────────
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " Apache Superset"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  printf "  ${YELLOW}The secret key encrypts all stored credentials."
  printf " Once set, it must never change.${NC}\n"

  prompt_value "Admin username" "admin"
  SUPERSET_ADMIN_USER="$_REPLY"

  prompt_value "Admin email" "$NOCODB_ADMIN_EMAIL"
  SUPERSET_ADMIN_EMAIL="$_REPLY"

  prompt_value "Admin password" "$(gen_secret)"
  SUPERSET_ADMIN_PASSWORD="$_REPLY"

  prompt_value "Secret key" "$(gen_secret)"
  SUPERSET_SECRET_KEY="$_REPLY"

  # ── Ports ────────────────────────────────────────────────
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " Ports"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  prompt_port "NocoDB port" "8080"
  NOCODB_PORT="$_REPLY"

  prompt_port "Superset port" "8088"
  SUPERSET_PORT="$_REPLY"
}

# ─── Summary ─────────────────────────────────────────────────

show_summary() {
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " Summary"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  printf "  %-28s %s\n" "PROJECT_NAME"           "$PROJECT_NAME"
  echo ""
  printf "  %-28s %s\n" "POSTGRES_USER"          "$POSTGRES_USER"
  printf "  %-28s %s\n" "POSTGRES_PASSWORD"      "$(mask "$POSTGRES_PASSWORD")"
  echo ""
  printf "  %-28s %s\n" "NOCODB_ADMIN_EMAIL"     "$NOCODB_ADMIN_EMAIL"
  printf "  %-28s %s\n" "NOCODB_ADMIN_PASSWORD"  "$(mask "$NOCODB_ADMIN_PASSWORD")"
  printf "  %-28s %s\n" "NOCODB_JWT_SECRET"      "$(mask "$NOCODB_JWT_SECRET")"
  echo ""
  printf "  %-28s %s\n" "SUPERSET_ADMIN_USER"    "$SUPERSET_ADMIN_USER"
  printf "  %-28s %s\n" "SUPERSET_ADMIN_EMAIL"   "$SUPERSET_ADMIN_EMAIL"
  printf "  %-28s %s\n" "SUPERSET_ADMIN_PASSWORD" "$(mask "$SUPERSET_ADMIN_PASSWORD")"
  printf "  %-28s %s\n" "SUPERSET_SECRET_KEY"    "$(mask "$SUPERSET_SECRET_KEY")"
  echo ""
  printf "  %-28s %s\n" "NOCODB_PORT"            "$NOCODB_PORT"
  printf "  %-28s %s\n" "SUPERSET_PORT"          "$SUPERSET_PORT"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  printf "  ${DIM}Passwords are masked. Full values are written to .env${NC}\n"
}

# ─── Write .env ──────────────────────────────────────────────

write_env() {
  cat > .env <<EOF
# ============================================================
# Lab Data Stack — Environment Variables
# Generated by install.sh on $(date)
# OS: $OS_NAME
# ============================================================
# NEVER commit this file to git.
# SUPERSET_SECRET_KEY must never be changed after first start.
# ============================================================

# ── PostgreSQL ───────────────────────────────────────────────
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# ── NocoDB ───────────────────────────────────────────────────
NOCODB_ADMIN_EMAIL=$NOCODB_ADMIN_EMAIL
NOCODB_ADMIN_PASSWORD=$NOCODB_ADMIN_PASSWORD
NOCODB_JWT_SECRET=$NOCODB_JWT_SECRET

# ── Apache Superset ──────────────────────────────────────────
SUPERSET_SECRET_KEY=$SUPERSET_SECRET_KEY
SUPERSET_ADMIN_USER=$SUPERSET_ADMIN_USER
SUPERSET_ADMIN_EMAIL=$SUPERSET_ADMIN_EMAIL
SUPERSET_ADMIN_PASSWORD=$SUPERSET_ADMIN_PASSWORD

# ── Ports ────────────────────────────────────────────────────
NOCODB_PORT=$NOCODB_PORT
SUPERSET_PORT=$SUPERSET_PORT

# ── Project ──────────────────────────────────────────────────
PROJECT_NAME=$PROJECT_NAME
EOF

  chmod 600 .env
}

# ─── Main ────────────────────────────────────────────────────

main() {
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  printf "  ${BOLD}Lab Data Stack — Installation${NC}  ${DIM}($OS_NAME)${NC}\n"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  check_dependencies

  if [ -f .env ]; then
    echo ""
    printf "  ${YELLOW}A .env file already exists.${NC}\n"
    printf "  Overwriting it will replace all current credentials.\n"
    printf "  Continue? [y/N] "
    read -r _confirm
    if [[ "$_confirm" != "y" && "$_confirm" != "Y" ]]; then
      echo "  Aborted. Existing .env left unchanged."
      echo ""
      exit 0
    fi
  fi

  while true; do
    collect_values
    show_summary

    echo ""
    printf "  Write .env and start the stack? [Y/n/r (restart prompts)] "
    read -r _choice
    echo ""

    case "$(printf '%s' "$_choice" | tr '[:upper:]' '[:lower:]')" in
      ""| y | yes)
        write_env
        echo ""
        printf "  ${GREEN}✓ .env written${NC}\n"
        echo ""
        ./start.sh
        exit 0
        ;;
      n | no)
        echo "  Aborted. No files written."
        echo ""
        exit 0
        ;;
      r | restart)
        echo "  Restarting prompts..."
        continue
        ;;
      *)
        echo "  Please enter y, n, or r."
        continue
        ;;
    esac
  done
}

main
